# Conclusions {.unnumbered #sec-conclusions}

## Final Answers

1. **Calculate the average annual deforestation rate overall (%/year) and per capita (ft²/year/capita) for all the counties in Georgia from 2001 and 2019.**
   - Calculated in the `forestrate0119` and `forestratecap0119` columns in `ga_counties`.
   - Negative values indicate deforestation while positive values indicate reforestation.

2. **Find which county has lost the most forest overall (%/year) and per capita (ft²/year/capita).**
   - The worst overall county is **Gwinnett**.
   - The worst per-capita county is **Clinch**.

3. **Find which county has lost the least or gained the most forest overall (%/year) and per capita (ft²/year/capita).**
   - The best overall county is **Terrell**.
   - The best per-capita county is **Lincoln**.

4. **Calculate the statewide annual average deforestation rate in percentage (%/year) and per capita (ft²/year/capita).**
   - The statewide annual average deforestation rate is **-0.28%/year**.
   - The statewide annual average deforestation rate per capita is **-213 ft²/year/capita**.

5. **Finally, report how many and percentage of counties are worse than the two statewide average rates.**
   - Total **73 counties (45.9%)** are worse than the statewide average deforestation rate.
   - Total **74 counties (46.5%)** are worse than the statewide average deforestation rate per capita.

## Future Considerations

Consider spatial forest disturbances induced by human activities.